moving uncheck items from previous day

diff --git a/scripts/obsidian_daily b/scripts/obsidian_daily
--- a/scripts/obsidian_daily
+++ b/scripts/obsidian_daily
@@ -14,19 +14,47 @@ daily_path=$HOME/Documents/second_brain/daily
 path=$HOME/Documents/second_brain/daily/${year}/${month}/${today}.md
 sb_path=$HOME/Documents/second_brain
 
-# Check if year and month exist for daily note
+# get unchecked items from the previous day
+get_unchecked_items() {
+  prev_date=$(date -d "yesterday" '+%Y-%m-%d-%A')
+  prev_year=$(date -d "yesterday" '+%Y')
+  prev_month=$(date -d "yesterday" '+$m-%B')
+  prev_path=$HOME/Documents/second_brain/daily/${prev_year}/${prev_month}/${prev_date}.md
+
+  if [ ! -f ${prev_path} ]; then
+    return
+  fi
+
+  sed -n '/### ❓ Daily Quests/,/---/p' ${prev_path} | grep '^\- \[ \]' >/tmp/unchecked_items.txt
+}
+
+# insert unchecked items from previous day
+insert_unchecked_items() {
+  if [ -s /tmp/unchecked_items.txt ]; then
+    sed -i '/### ❓ Daily Quests/r /tmp/unchecked_items.txt' ${path}
+    rm /tmp/unchecked_items.txt
+  fi
+}
+
+# check if year and month exist for daily note
 if [ ! -d ${sb_path}/daily/${year} ]; then
-	mkdir ${sb_path}/daily/${year}
+  mkdir ${sb_path}/daily/${year}
 fi
+# check if month exists
 if [ ! -d ${sb_path}/daily/${year}/${month} ]; then
-	mkdir ${sb_path}/daily/${year}/${month}
+  mkdir ${sb_path}/daily/${year}/${month}
 fi
+# check if whole path to daily note exists
 if [ ! -f ${path} ]; then
-	echo "Daily note not found. Attempting to make now..."
-	if [ ! -d ${sb_path} ]; then
-		echo "Template not found. Looks like your vault is jacked up..."
-	fi
-	cp ${template_path} ${path}
+  echo "Daily note not found. Attempting to make now..."
+  # check if template exists
+  if [ ! -d ${sb_path} ]; then
+    echo "Template not found. Looks like your vault is jacked up..."
+    exit 1
+  fi
+  cp ${template_path} ${path}
+  get_unchecked_items
+  insert_unchecked_items
 fi
 
 nvim ${path}
